#-------------------------------------------
# InvoiceShelf docker-compose variant for
# docker image development/testing purposes.
#-------------------------------------------
# What it does:
# - This is not intended to be used in PRODUCTION
# - Builds the Dockerfile instead of using pre-built
#   one from Dockerhub.
#-------------------------------------------
# Repo : https://github.com/InvoiceShelf/docker
#-------------------------------------------

services:
  invoiceshelf:
    image: invoiceshelf
    build:
      context: .
      dockerfile: Dockerfile

    container_name: invoiceshelf
    ports:
      - 90:80
    volumes:
      - ./invoiceshelf_supabase/data:/data
      - ./invoiceshelf_supabase/conf:/conf
    networks:
      - invoiceshelf
    environment:
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:90
      - DB_CONNECTION=pgsql
      - DB_HOST=db.your-host.supabase.co
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=YourPass
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:90
      - STARTUP_DELAY=
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
    restart: unless-stopped

networks:
  invoiceshelf:
